<a href="https://colab.research.google.com/github/davidlealo/sic_ai_2025_jun/blob/main/clase_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### SIC JUNIO 2025
# Clase 2

## Tipo de datos


In [22]:
nombre = "David"
edad = 40
estatura = 1.75
despierto = True

In [2]:
print(type(nombre))

<class 'str'>


In [3]:
print(type(edad))

<class 'int'>


In [4]:
print(type(estatura))

<class 'float'>


In [5]:
print(type(despierto))

<class 'bool'>


EJEMPLO: Vamos a trabajar con un algoritmo para predecir si mañana va a llover, pero hya un dato importante que es el clima del lugar:

1. Tropical
2. Seco
3. Mediterraneo

| Región | Tropical | Seco | Mediterráneo |
|--------|----------|------|--------------|
| A      |    1     |  0   |      0       |
| B      |    0     |  1   |      0       |
| C      |    0     |  0   |      1       |
| D      |    1     |  0   |      0       |
| E      |    0     |  1   |      0       |
| F      |    0     |  0   |      1       |




In [6]:
!python --version

Python 3.11.13


In [3]:
nombre

'David'

## Numpy

In [ ]:
!pip install numpy

In [4]:
#Importar numpy
import numpy

In [5]:
numpy.__version__

'2.0.2'

In [1]:
!pip install --upgrade numpy

In [2]:
import numpy
numpy.__version__

'2.3.1'

In [3]:
import numpy as pepito

In [4]:
pepito.__version__

'2.3.1'

In [5]:
import numpy as np
np.__version__

'2.3.1'

In [24]:
nombre = "Elias"

#### arrays en numpy

In [6]:
lista = [1,2,3,4,5,6,7,8,9,10]

In [7]:
print(type(lista))

<class 'list'>


In [9]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
np.array(lista)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr1 = np.array(lista)

In [11]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
print(type(arr1))

<class 'numpy.ndarray'>


In [13]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])

In [14]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
id(lista)

133737623098560

In [16]:
id(arr1)

133737834560464

In [17]:
id(arr2)

133737834627312

In [18]:
arr3 = arr1

In [19]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
print(id(arr1))
print(id(arr3))

133737834560464
133737834560464


In [25]:
nombre

'Elias'

#### Cambio de valores

In [26]:
ar1 = np.array([1,2,3,10])

In [27]:
id(ar1)

133737834813392

In [28]:
ar2 = ar1

In [29]:
id(ar2)

133737834813392

In [30]:
ar2

array([ 1,  2,  3, 10])

In [31]:
ar1 = np.array([1,2,3,4])

In [32]:
ar1

array([1, 2, 3, 4])

In [33]:
id(ar1)

133737834822224

In [34]:
ar2

array([ 1,  2,  3, 10])

In [35]:
id(ar2)

133737834813392

In [36]:
ar1

array([1, 2, 3, 4])

In [37]:
ar1 = "Estamos en clases de Samsung Innovation Campus"

In [38]:
ar1

'Estamos en clases de Samsung Innovation Campus'

In [39]:
id(ar1)

133737835452176

In [40]:
ar2

array([ 1,  2,  3, 10])