<a href="https://colab.research.google.com/github/davidlealo/sic_ai_2025_jun/blob/main/clase_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### SIC JUNIO 2025
# Clase 2

## Tipo de datos


In [22]:
nombre = "David"
edad = 40
estatura = 1.75
despierto = True

In [2]:
print(type(nombre))

<class 'str'>


In [3]:
print(type(edad))

<class 'int'>


In [4]:
print(type(estatura))

<class 'float'>


In [5]:
print(type(despierto))

<class 'bool'>


EJEMPLO: Vamos a trabajar con un algoritmo para predecir si mañana va a llover, pero hya un dato importante que es el clima del lugar:

1. Tropical
2. Seco
3. Mediterraneo

| Región | Tropical | Seco | Mediterráneo |
|--------|----------|------|--------------|
| A      |    1     |  0   |      0       |
| B      |    0     |  1   |      0       |
| C      |    0     |  0   |      1       |
| D      |    1     |  0   |      0       |
| E      |    0     |  1   |      0       |
| F      |    0     |  0   |      1       |




In [6]:
!python --version

Python 3.11.13


In [3]:
nombre

'David'

## Numpy

In [ ]:
!pip install numpy

In [4]:
#Importar numpy
import numpy

In [5]:
numpy.__version__

'2.0.2'

In [1]:
!pip install --upgrade numpy

In [2]:
import numpy
numpy.__version__

'2.3.1'

In [3]:
import numpy as pepito

In [4]:
pepito.__version__

'2.3.1'

In [5]:
import numpy as np
np.__version__

'2.3.1'

In [24]:
nombre = "Elias"

#### arrays en numpy

In [6]:
lista = [1,2,3,4,5,6,7,8,9,10]

In [7]:
print(type(lista))

<class 'list'>


In [9]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
np.array(lista)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr1 = np.array(lista)

In [11]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
print(type(arr1))

<class 'numpy.ndarray'>


In [13]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])

In [14]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
id(lista)

133737623098560

In [16]:
id(arr1)

133737834560464

In [17]:
id(arr2)

133737834627312

In [18]:
arr3 = arr1

In [19]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
print(id(arr1))
print(id(arr3))

133737834560464
133737834560464


In [25]:
nombre

'Elias'

#### Cambio de valores

In [26]:
ar1 = np.array([1,2,3,10])

In [27]:
id(ar1)

133737834813392

In [28]:
ar2 = ar1

In [29]:
id(ar2)

133737834813392

In [30]:
ar2

array([ 1,  2,  3, 10])

In [31]:
ar1 = np.array([1,2,3,4])

In [32]:
ar1

array([1, 2, 3, 4])

In [33]:
id(ar1)

133737834822224

In [34]:
ar2

array([ 1,  2,  3, 10])

In [35]:
id(ar2)

133737834813392

In [36]:
ar1

array([1, 2, 3, 4])

In [37]:
ar1 = "Estamos en clases de Samsung Innovation Campus"

In [38]:
ar1

'Estamos en clases de Samsung Innovation Campus'

In [39]:
id(ar1)

133737835452176

In [40]:
ar2

array([ 1,  2,  3, 10])

#### ver index en arrays de numpy

In [41]:
a = np.array([1, 2, 3, 4, 5, 6])

In [42]:
a

array([1, 2, 3, 4, 5, 6])

In [43]:
a[0]

np.int64(1)

In [44]:
a[1]

np.int64(2)

In [45]:
a[-1]

np.int64(6)

In [46]:
a[-2]

np.int64(5)

In [47]:
a[-6]

np.int64(1)

#### copiar un valor con numpy

In [48]:
arr1 = np.array([1,2,3,4,5])

In [49]:
arr1

array([1, 2, 3, 4, 5])

In [50]:
id(arr1)

133737834825744

In [51]:
arr2 = np.copy(arr1)

In [52]:
arr2

array([1, 2, 3, 4, 5])

In [53]:
id(arr2)

133737844623376

In [54]:
arr3 = arr1

In [55]:
id(arr3)

133737834825744

#### organizar datos

In [56]:
numeros = np.array([1,12,2,3,4,5,1,22,4,5,6,7,8,9,10])

In [57]:
numeros.sort()

In [59]:
numeros

array([ 1,  1,  2,  3,  4,  4,  5,  5,  6,  7,  8,  9, 10, 12, 22])

### Crear arrays de numpy desde tuplas

In [60]:
tupla = (1,2,3,4,5,6,7,8,9,10)

In [61]:
id(tupla)

133737844679744

In [62]:
print(type(tupla))

<class 'tuple'>


In [63]:
tupla

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [65]:
tupla_array = np.array(tupla)

In [66]:
id(tupla_array)

133737843982032

In [67]:
print(type(tupla_array))

<class 'numpy.ndarray'>


In [68]:
tupla_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Crear arrays de numpy desde diccionarios

In [69]:
diccionario = {"a":1, "b":2, "c":3, "d":4, "e":5}

In [70]:
print(type(diccionario))

<class 'dict'>


In [71]:
dic_array = np.array(diccionario)

In [72]:
print(type(dic_array))

<class 'numpy.ndarray'>


In [73]:
dic_array

array({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}, dtype=object)

In [74]:
dic_array[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

#### Crear arrays de numpy en un rango


Ver link https://numpy.org/doc/stable/reference/generated/numpy.arange.html

In [75]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr2 = np.arange(4,10)
arr2

array([4, 5, 6, 7, 8, 9])

In [79]:
arr3 = np.arange(4,10,2)
arr3

array([4, 6, 8])

#### Ver la extensión de arrays de numpy

In [80]:
arr1 = np.arange(10)

In [82]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
len(arr1)

10

In [84]:
arr1.size

10

In [86]:
a2 = 1
a3 = 2
a4 = 3

In [87]:
lista = [a2,a3,a4]

In [88]:
lista

[1, 2, 3]

In [89]:
# Agregar numeros a lista 4, 5, 6, 7, 8, 9, 10
lista.append(4)
lista.append(5)
lista.append(6)
lista.append(7)
lista.append(8)
lista.append(9)
lista.append(10)

In [90]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### reshape

In [91]:
ej1 = np.arange(15)

In [92]:
ej1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [93]:
ej1.shape

(15,)

In [94]:
ej2 = ej1.reshape(3,5)

In [95]:
ej2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [96]:
ej2.shape

(3, 5)

In [97]:
ej3 = ej1.reshape(5,3)

In [98]:
ej3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])